### PR TITLE
Add TLS support

### PR DESCRIPTION
**Pull request by brianshannan-wf**
Adds TLS support
- Some general code cleanup like removing unused imports and code deduplication
- Added certs/keys from the nats tornado library for testing
- Updated the travis distro to what the nats tornado library was it appeared the default had an old ssl version

I'll pr this upstream if this looks good to you guys

@Workiva/messaging-pp

### CODE REVIEW

**Comment by brianshannan-wf** [comment]
@stevenosborne-wf @tylerrinnan-wf @charliestrawn-wf @jacobmoss-wf @tylertreat-wf @aldenpeterson-wf

**Comment by charliestrawn-wf** [comment]
+1

**Comment by tylertreat-wf** [comment]
Have you talked to @wallyqs at all?

**Comment by charliestrawn-wf** [comment]
Yeah, he said https://github.com/python/asyncio/issues/79 needed to be resolved or the connect logic needed to be refactored.  Said he would take a look, but I figured with this small of a change we could just make a PR and see what he thinks.

**Pull request closed without merging**
